// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/crafty-ezhik/rocket-factory/inventory/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryRepository creates a new instance of MockInventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryRepository {
	mock := &MockInventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryRepository is an autogenerated mock type for the InventoryRepository type
type MockInventoryRepository struct {
	mock.Mock
}

type MockInventoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryRepository) EXPECT() *MockInventoryRepository_Expecter {
	return &MockInventoryRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockInventoryRepository
func (_mock *MockInventoryRepository) Get(ctx context.Context, partID uuid.UUID) (model.Part, error) {
	ret := _mock.Called(ctx, partID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Part, error)); ok {
		return returnFunc(ctx, partID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Part); ok {
		r0 = returnFunc(ctx, partID)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, partID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockInventoryRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - partID uuid.UUID
func (_e *MockInventoryRepository_Expecter) Get(ctx interface{}, partID interface{}) *MockInventoryRepository_Get_Call {
	return &MockInventoryRepository_Get_Call{Call: _e.mock.On("Get", ctx, partID)}
}

func (_c *MockInventoryRepository_Get_Call) Run(run func(ctx context.Context, partID uuid.UUID)) *MockInventoryRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryRepository_Get_Call) Return(part model.Part, err error) *MockInventoryRepository_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockInventoryRepository_Get_Call) RunAndReturn(run func(ctx context.Context, partID uuid.UUID) (model.Part, error)) *MockInventoryRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockInventoryRepository
func (_mock *MockInventoryRepository) Init(n int) {
	_mock.Called(n)
	return
}

// MockInventoryRepository_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockInventoryRepository_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - n int
func (_e *MockInventoryRepository_Expecter) Init(n interface{}) *MockInventoryRepository_Init_Call {
	return &MockInventoryRepository_Init_Call{Call: _e.mock.On("Init", n)}
}

func (_c *MockInventoryRepository_Init_Call) Run(run func(n int)) *MockInventoryRepository_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInventoryRepository_Init_Call) Return() *MockInventoryRepository_Init_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInventoryRepository_Init_Call) RunAndReturn(run func(n int)) *MockInventoryRepository_Init_Call {
	_c.Run(run)
	return _c
}

// List provides a mock function for the type MockInventoryRepository
func (_mock *MockInventoryRepository) List(ctx context.Context, filters model.PartsFilter) ([]model.Part, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartsFilter) ([]model.Part, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartsFilter) []model.Part); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockInventoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filters model.PartsFilter
func (_e *MockInventoryRepository_Expecter) List(ctx interface{}, filters interface{}) *MockInventoryRepository_List_Call {
	return &MockInventoryRepository_List_Call{Call: _e.mock.On("List", ctx, filters)}
}

func (_c *MockInventoryRepository_List_Call) Run(run func(ctx context.Context, filters model.PartsFilter)) *MockInventoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PartsFilter
		if args[1] != nil {
			arg1 = args[1].(model.PartsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryRepository_List_Call) Return(parts []model.Part, err error) *MockInventoryRepository_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *MockInventoryRepository_List_Call) RunAndReturn(run func(ctx context.Context, filters model.PartsFilter) ([]model.Part, error)) *MockInventoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
