// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderConsumerConfig creates a new instance of MockOrderConsumerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderConsumerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderConsumerConfig {
	mock := &MockOrderConsumerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderConsumerConfig is an autogenerated mock type for the OrderConsumerConfig type
type MockOrderConsumerConfig struct {
	mock.Mock
}

type MockOrderConsumerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderConsumerConfig) EXPECT() *MockOrderConsumerConfig_Expecter {
	return &MockOrderConsumerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockOrderConsumerConfig
func (_mock *MockOrderConsumerConfig) Config() *sarama.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if returnFunc, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}
	return r0
}

// MockOrderConsumerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockOrderConsumerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockOrderConsumerConfig_Expecter) Config() *MockOrderConsumerConfig_Config_Call {
	return &MockOrderConsumerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockOrderConsumerConfig_Config_Call) Run(run func()) *MockOrderConsumerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderConsumerConfig_Config_Call) Return(config *sarama.Config) *MockOrderConsumerConfig_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockOrderConsumerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *MockOrderConsumerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GroupID provides a mock function for the type MockOrderConsumerConfig
func (_mock *MockOrderConsumerConfig) GroupID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOrderConsumerConfig_GroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupID'
type MockOrderConsumerConfig_GroupID_Call struct {
	*mock.Call
}

// GroupID is a helper method to define mock.On call
func (_e *MockOrderConsumerConfig_Expecter) GroupID() *MockOrderConsumerConfig_GroupID_Call {
	return &MockOrderConsumerConfig_GroupID_Call{Call: _e.mock.On("GroupID")}
}

func (_c *MockOrderConsumerConfig_GroupID_Call) Run(run func()) *MockOrderConsumerConfig_GroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderConsumerConfig_GroupID_Call) Return(s string) *MockOrderConsumerConfig_GroupID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOrderConsumerConfig_GroupID_Call) RunAndReturn(run func() string) *MockOrderConsumerConfig_GroupID_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function for the type MockOrderConsumerConfig
func (_mock *MockOrderConsumerConfig) Topic() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOrderConsumerConfig_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type MockOrderConsumerConfig_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *MockOrderConsumerConfig_Expecter) Topic() *MockOrderConsumerConfig_Topic_Call {
	return &MockOrderConsumerConfig_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *MockOrderConsumerConfig_Topic_Call) Run(run func()) *MockOrderConsumerConfig_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderConsumerConfig_Topic_Call) Return(s string) *MockOrderConsumerConfig_Topic_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOrderConsumerConfig_Topic_Call) RunAndReturn(run func() string) *MockOrderConsumerConfig_Topic_Call {
	_c.Call.Return(run)
	return _c
}
