// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTelegramBotConfig creates a new instance of MockTelegramBotConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelegramBotConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelegramBotConfig {
	mock := &MockTelegramBotConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelegramBotConfig is an autogenerated mock type for the TelegramBotConfig type
type MockTelegramBotConfig struct {
	mock.Mock
}

type MockTelegramBotConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelegramBotConfig) EXPECT() *MockTelegramBotConfig_Expecter {
	return &MockTelegramBotConfig_Expecter{mock: &_m.Mock}
}

// ChatID provides a mock function for the type MockTelegramBotConfig
func (_mock *MockTelegramBotConfig) ChatID() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChatID")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockTelegramBotConfig_ChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatID'
type MockTelegramBotConfig_ChatID_Call struct {
	*mock.Call
}

// ChatID is a helper method to define mock.On call
func (_e *MockTelegramBotConfig_Expecter) ChatID() *MockTelegramBotConfig_ChatID_Call {
	return &MockTelegramBotConfig_ChatID_Call{Call: _e.mock.On("ChatID")}
}

func (_c *MockTelegramBotConfig_ChatID_Call) Run(run func()) *MockTelegramBotConfig_ChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelegramBotConfig_ChatID_Call) Return(n int64) *MockTelegramBotConfig_ChatID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockTelegramBotConfig_ChatID_Call) RunAndReturn(run func() int64) *MockTelegramBotConfig_ChatID_Call {
	_c.Call.Return(run)
	return _c
}

// Token provides a mock function for the type MockTelegramBotConfig
func (_mock *MockTelegramBotConfig) Token() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Token")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTelegramBotConfig_Token_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Token'
type MockTelegramBotConfig_Token_Call struct {
	*mock.Call
}

// Token is a helper method to define mock.On call
func (_e *MockTelegramBotConfig_Expecter) Token() *MockTelegramBotConfig_Token_Call {
	return &MockTelegramBotConfig_Token_Call{Call: _e.mock.On("Token")}
}

func (_c *MockTelegramBotConfig_Token_Call) Run(run func()) *MockTelegramBotConfig_Token_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelegramBotConfig_Token_Call) Return(s string) *MockTelegramBotConfig_Token_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTelegramBotConfig_Token_Call) RunAndReturn(run func() string) *MockTelegramBotConfig_Token_Call {
	_c.Call.Return(run)
	return _c
}
