// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/crafty-ezhik/rocket-factory/iam/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, login string, password string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx interface{}, login interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, login, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, login string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(uUID uuid.UUID, err error) *MockAuthService_Login_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, login string, password string) (uuid.UUID, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Whoami provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Whoami(ctx context.Context, sessionUUID uuid.UUID) (model.WhoamiResponse, error) {
	ret := _mock.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 model.WhoamiResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.WhoamiResponse, error)); ok {
		return returnFunc(ctx, sessionUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.WhoamiResponse); ok {
		r0 = returnFunc(ctx, sessionUUID)
	} else {
		r0 = ret.Get(0).(model.WhoamiResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Whoami_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Whoami'
type MockAuthService_Whoami_Call struct {
	*mock.Call
}

// Whoami is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID uuid.UUID
func (_e *MockAuthService_Expecter) Whoami(ctx interface{}, sessionUUID interface{}) *MockAuthService_Whoami_Call {
	return &MockAuthService_Whoami_Call{Call: _e.mock.On("Whoami", ctx, sessionUUID)}
}

func (_c *MockAuthService_Whoami_Call) Run(run func(ctx context.Context, sessionUUID uuid.UUID)) *MockAuthService_Whoami_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Whoami_Call) Return(whoamiResponse model.WhoamiResponse, err error) *MockAuthService_Whoami_Call {
	_c.Call.Return(whoamiResponse, err)
	return _c
}

func (_c *MockAuthService_Whoami_Call) RunAndReturn(run func(ctx context.Context, sessionUUID uuid.UUID) (model.WhoamiResponse, error)) *MockAuthService_Whoami_Call {
	_c.Call.Return(run)
	return _c
}
