// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/crafty-ezhik/rocket-factory/iam/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockUserService
func (_mock *MockUserService) Get(ctx context.Context, userUUID uuid.UUID) (model.User, error) {
	ret := _mock.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.User, error)); ok {
		return returnFunc(ctx, userUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.User); ok {
		r0 = returnFunc(ctx, userUUID)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
func (_e *MockUserService_Expecter) Get(ctx interface{}, userUUID interface{}) *MockUserService_Get_Call {
	return &MockUserService_Get_Call{Call: _e.mock.On("Get", ctx, userUUID)}
}

func (_c *MockUserService_Get_Call) Run(run func(ctx context.Context, userUUID uuid.UUID)) *MockUserService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Get_Call) Return(user model.User, err error) *MockUserService_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_Get_Call) RunAndReturn(run func(ctx context.Context, userUUID uuid.UUID) (model.User, error)) *MockUserService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserService
func (_mock *MockUserService) Register(ctx context.Context, userInfo model.UserRegistrationInfo) (uuid.UUID, error) {
	ret := _mock.Called(ctx, userInfo)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserRegistrationInfo) (uuid.UUID, error)); ok {
		return returnFunc(ctx, userInfo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserRegistrationInfo) uuid.UUID); ok {
		r0 = returnFunc(ctx, userInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserRegistrationInfo) error); ok {
		r1 = returnFunc(ctx, userInfo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - userInfo model.UserRegistrationInfo
func (_e *MockUserService_Expecter) Register(ctx interface{}, userInfo interface{}) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", ctx, userInfo)}
}

func (_c *MockUserService_Register_Call) Run(run func(ctx context.Context, userInfo model.UserRegistrationInfo)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserRegistrationInfo
		if args[1] != nil {
			arg1 = args[1].(model.UserRegistrationInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(uUID uuid.UUID, err error) *MockUserService_Register_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(ctx context.Context, userInfo model.UserRegistrationInfo) (uuid.UUID, error)) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}
