// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockGRPCConfig creates a new instance of MockGRPCConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGRPCConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGRPCConfig {
	mock := &MockGRPCConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGRPCConfig is an autogenerated mock type for the GRPCConfig type
type MockGRPCConfig struct {
	mock.Mock
}

type MockGRPCConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGRPCConfig) EXPECT() *MockGRPCConfig_Expecter {
	return &MockGRPCConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockGRPCConfig
func (_mock *MockGRPCConfig) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGRPCConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockGRPCConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockGRPCConfig_Expecter) Address() *MockGRPCConfig_Address_Call {
	return &MockGRPCConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockGRPCConfig_Address_Call) Run(run func()) *MockGRPCConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGRPCConfig_Address_Call) Return(s string) *MockGRPCConfig_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGRPCConfig_Address_Call) RunAndReturn(run func() string) *MockGRPCConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// Host provides a mock function for the type MockGRPCConfig
func (_mock *MockGRPCConfig) Host() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGRPCConfig_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type MockGRPCConfig_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *MockGRPCConfig_Expecter) Host() *MockGRPCConfig_Host_Call {
	return &MockGRPCConfig_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *MockGRPCConfig_Host_Call) Run(run func()) *MockGRPCConfig_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGRPCConfig_Host_Call) Return(s string) *MockGRPCConfig_Host_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGRPCConfig_Host_Call) RunAndReturn(run func() string) *MockGRPCConfig_Host_Call {
	_c.Call.Return(run)
	return _c
}

// Port provides a mock function for the type MockGRPCConfig
func (_mock *MockGRPCConfig) Port() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Port")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGRPCConfig_Port_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Port'
type MockGRPCConfig_Port_Call struct {
	*mock.Call
}

// Port is a helper method to define mock.On call
func (_e *MockGRPCConfig_Expecter) Port() *MockGRPCConfig_Port_Call {
	return &MockGRPCConfig_Port_Call{Call: _e.mock.On("Port")}
}

func (_c *MockGRPCConfig_Port_Call) Run(run func()) *MockGRPCConfig_Port_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGRPCConfig_Port_Call) Return(s string) *MockGRPCConfig_Port_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGRPCConfig_Port_Call) RunAndReturn(run func() string) *MockGRPCConfig_Port_Call {
	_c.Call.Return(run)
	return _c
}
