// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionConfig creates a new instance of MockSessionConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionConfig {
	mock := &MockSessionConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionConfig is an autogenerated mock type for the SessionConfig type
type MockSessionConfig struct {
	mock.Mock
}

type MockSessionConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionConfig) EXPECT() *MockSessionConfig_Expecter {
	return &MockSessionConfig_Expecter{mock: &_m.Mock}
}

// TTL provides a mock function for the type MockSessionConfig
func (_mock *MockSessionConfig) TTL() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TTL")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockSessionConfig_TTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TTL'
type MockSessionConfig_TTL_Call struct {
	*mock.Call
}

// TTL is a helper method to define mock.On call
func (_e *MockSessionConfig_Expecter) TTL() *MockSessionConfig_TTL_Call {
	return &MockSessionConfig_TTL_Call{Call: _e.mock.On("TTL")}
}

func (_c *MockSessionConfig_TTL_Call) Run(run func()) *MockSessionConfig_TTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionConfig_TTL_Call) Return(duration time.Duration) *MockSessionConfig_TTL_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockSessionConfig_TTL_Call) RunAndReturn(run func() time.Duration) *MockSessionConfig_TTL_Call {
	_c.Call.Return(run)
	return _c
}
