// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRedisConfig creates a new instance of MockRedisConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisConfig {
	mock := &MockRedisConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedisConfig is an autogenerated mock type for the RedisConfig type
type MockRedisConfig struct {
	mock.Mock
}

type MockRedisConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisConfig) EXPECT() *MockRedisConfig_Expecter {
	return &MockRedisConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockRedisConfig
func (_mock *MockRedisConfig) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRedisConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockRedisConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockRedisConfig_Expecter) Address() *MockRedisConfig_Address_Call {
	return &MockRedisConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockRedisConfig_Address_Call) Run(run func()) *MockRedisConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisConfig_Address_Call) Return(s string) *MockRedisConfig_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRedisConfig_Address_Call) RunAndReturn(run func() string) *MockRedisConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectionTimeout provides a mock function for the type MockRedisConfig
func (_mock *MockRedisConfig) ConnectionTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConnectionTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockRedisConfig_ConnectionTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectionTimeout'
type MockRedisConfig_ConnectionTimeout_Call struct {
	*mock.Call
}

// ConnectionTimeout is a helper method to define mock.On call
func (_e *MockRedisConfig_Expecter) ConnectionTimeout() *MockRedisConfig_ConnectionTimeout_Call {
	return &MockRedisConfig_ConnectionTimeout_Call{Call: _e.mock.On("ConnectionTimeout")}
}

func (_c *MockRedisConfig_ConnectionTimeout_Call) Run(run func()) *MockRedisConfig_ConnectionTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisConfig_ConnectionTimeout_Call) Return(duration time.Duration) *MockRedisConfig_ConnectionTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockRedisConfig_ConnectionTimeout_Call) RunAndReturn(run func() time.Duration) *MockRedisConfig_ConnectionTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// Host provides a mock function for the type MockRedisConfig
func (_mock *MockRedisConfig) Host() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRedisConfig_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type MockRedisConfig_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *MockRedisConfig_Expecter) Host() *MockRedisConfig_Host_Call {
	return &MockRedisConfig_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *MockRedisConfig_Host_Call) Run(run func()) *MockRedisConfig_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisConfig_Host_Call) Return(s string) *MockRedisConfig_Host_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRedisConfig_Host_Call) RunAndReturn(run func() string) *MockRedisConfig_Host_Call {
	_c.Call.Return(run)
	return _c
}

// IdleTimeout provides a mock function for the type MockRedisConfig
func (_mock *MockRedisConfig) IdleTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IdleTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockRedisConfig_IdleTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdleTimeout'
type MockRedisConfig_IdleTimeout_Call struct {
	*mock.Call
}

// IdleTimeout is a helper method to define mock.On call
func (_e *MockRedisConfig_Expecter) IdleTimeout() *MockRedisConfig_IdleTimeout_Call {
	return &MockRedisConfig_IdleTimeout_Call{Call: _e.mock.On("IdleTimeout")}
}

func (_c *MockRedisConfig_IdleTimeout_Call) Run(run func()) *MockRedisConfig_IdleTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisConfig_IdleTimeout_Call) Return(duration time.Duration) *MockRedisConfig_IdleTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockRedisConfig_IdleTimeout_Call) RunAndReturn(run func() time.Duration) *MockRedisConfig_IdleTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// MaxIdle provides a mock function for the type MockRedisConfig
func (_mock *MockRedisConfig) MaxIdle() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxIdle")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockRedisConfig_MaxIdle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxIdle'
type MockRedisConfig_MaxIdle_Call struct {
	*mock.Call
}

// MaxIdle is a helper method to define mock.On call
func (_e *MockRedisConfig_Expecter) MaxIdle() *MockRedisConfig_MaxIdle_Call {
	return &MockRedisConfig_MaxIdle_Call{Call: _e.mock.On("MaxIdle")}
}

func (_c *MockRedisConfig_MaxIdle_Call) Run(run func()) *MockRedisConfig_MaxIdle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisConfig_MaxIdle_Call) Return(n int) *MockRedisConfig_MaxIdle_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockRedisConfig_MaxIdle_Call) RunAndReturn(run func() int) *MockRedisConfig_MaxIdle_Call {
	_c.Call.Return(run)
	return _c
}

// Port provides a mock function for the type MockRedisConfig
func (_mock *MockRedisConfig) Port() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Port")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRedisConfig_Port_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Port'
type MockRedisConfig_Port_Call struct {
	*mock.Call
}

// Port is a helper method to define mock.On call
func (_e *MockRedisConfig_Expecter) Port() *MockRedisConfig_Port_Call {
	return &MockRedisConfig_Port_Call{Call: _e.mock.On("Port")}
}

func (_c *MockRedisConfig_Port_Call) Run(run func()) *MockRedisConfig_Port_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisConfig_Port_Call) Return(s string) *MockRedisConfig_Port_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRedisConfig_Port_Call) RunAndReturn(run func() string) *MockRedisConfig_Port_Call {
	_c.Call.Return(run)
	return _c
}
