// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryHTTPConfig creates a new instance of MockInventoryHTTPConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryHTTPConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryHTTPConfig {
	mock := &MockInventoryHTTPConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryHTTPConfig is an autogenerated mock type for the InventoryHTTPConfig type
type MockInventoryHTTPConfig struct {
	mock.Mock
}

type MockInventoryHTTPConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryHTTPConfig) EXPECT() *MockInventoryHTTPConfig_Expecter {
	return &MockInventoryHTTPConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockInventoryHTTPConfig
func (_mock *MockInventoryHTTPConfig) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockInventoryHTTPConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockInventoryHTTPConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockInventoryHTTPConfig_Expecter) Address() *MockInventoryHTTPConfig_Address_Call {
	return &MockInventoryHTTPConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockInventoryHTTPConfig_Address_Call) Run(run func()) *MockInventoryHTTPConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInventoryHTTPConfig_Address_Call) Return(s string) *MockInventoryHTTPConfig_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockInventoryHTTPConfig_Address_Call) RunAndReturn(run func() string) *MockInventoryHTTPConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}
