// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoggerConfig creates a new instance of MockLoggerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerConfig {
	mock := &MockLoggerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoggerConfig is an autogenerated mock type for the LoggerConfig type
type MockLoggerConfig struct {
	mock.Mock
}

type MockLoggerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerConfig) EXPECT() *MockLoggerConfig_Expecter {
	return &MockLoggerConfig_Expecter{mock: &_m.Mock}
}

// AsJSON provides a mock function for the type MockLoggerConfig
func (_mock *MockLoggerConfig) AsJSON() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AsJSON")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockLoggerConfig_AsJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsJSON'
type MockLoggerConfig_AsJSON_Call struct {
	*mock.Call
}

// AsJSON is a helper method to define mock.On call
func (_e *MockLoggerConfig_Expecter) AsJSON() *MockLoggerConfig_AsJSON_Call {
	return &MockLoggerConfig_AsJSON_Call{Call: _e.mock.On("AsJSON")}
}

func (_c *MockLoggerConfig_AsJSON_Call) Run(run func()) *MockLoggerConfig_AsJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerConfig_AsJSON_Call) Return(b bool) *MockLoggerConfig_AsJSON_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockLoggerConfig_AsJSON_Call) RunAndReturn(run func() bool) *MockLoggerConfig_AsJSON_Call {
	_c.Call.Return(run)
	return _c
}

// Level provides a mock function for the type MockLoggerConfig
func (_mock *MockLoggerConfig) Level() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Level")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockLoggerConfig_Level_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Level'
type MockLoggerConfig_Level_Call struct {
	*mock.Call
}

// Level is a helper method to define mock.On call
func (_e *MockLoggerConfig_Expecter) Level() *MockLoggerConfig_Level_Call {
	return &MockLoggerConfig_Level_Call{Call: _e.mock.On("Level")}
}

func (_c *MockLoggerConfig_Level_Call) Run(run func()) *MockLoggerConfig_Level_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerConfig_Level_Call) Return(s string) *MockLoggerConfig_Level_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockLoggerConfig_Level_Call) RunAndReturn(run func() string) *MockLoggerConfig_Level_Call {
	_c.Call.Return(run)
	return _c
}
