// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/crafty-ezhik/rocket-factory/iam/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// AddToUserSet provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) AddToUserSet(ctx context.Context, userUUID uuid.UUID, sessionUUID uuid.UUID) error {
	ret := _mock.Called(ctx, userUUID, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for AddToUserSet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userUUID, sessionUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_AddToUserSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToUserSet'
type MockSessionRepository_AddToUserSet_Call struct {
	*mock.Call
}

// AddToUserSet is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
//   - sessionUUID uuid.UUID
func (_e *MockSessionRepository_Expecter) AddToUserSet(ctx interface{}, userUUID interface{}, sessionUUID interface{}) *MockSessionRepository_AddToUserSet_Call {
	return &MockSessionRepository_AddToUserSet_Call{Call: _e.mock.On("AddToUserSet", ctx, userUUID, sessionUUID)}
}

func (_c *MockSessionRepository_AddToUserSet_Call) Run(run func(ctx context.Context, userUUID uuid.UUID, sessionUUID uuid.UUID)) *MockSessionRepository_AddToUserSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_AddToUserSet_Call) Return(err error) *MockSessionRepository_AddToUserSet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_AddToUserSet_Call) RunAndReturn(run func(ctx context.Context, userUUID uuid.UUID, sessionUUID uuid.UUID) error) *MockSessionRepository_AddToUserSet_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Create(ctx context.Context, userUUID uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, userUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, userUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
func (_e *MockSessionRepository_Expecter) Create(ctx interface{}, userUUID interface{}) *MockSessionRepository_Create_Call {
	return &MockSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, userUUID)}
}

func (_c *MockSessionRepository_Create_Call) Run(run func(ctx context.Context, userUUID uuid.UUID)) *MockSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Create_Call) Return(uUID uuid.UUID, err error) *MockSessionRepository_Create_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockSessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userUUID uuid.UUID) (uuid.UUID, error)) *MockSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Get(ctx context.Context, sessionUUID uuid.UUID) (model.Session, error) {
	ret := _mock.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Session, error)); ok {
		return returnFunc(ctx, sessionUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Session); ok {
		r0 = returnFunc(ctx, sessionUUID)
	} else {
		r0 = ret.Get(0).(model.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID uuid.UUID
func (_e *MockSessionRepository_Expecter) Get(ctx interface{}, sessionUUID interface{}) *MockSessionRepository_Get_Call {
	return &MockSessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, sessionUUID)}
}

func (_c *MockSessionRepository_Get_Call) Run(run func(ctx context.Context, sessionUUID uuid.UUID)) *MockSessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Get_Call) Return(session model.Session, err error) *MockSessionRepository_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_Get_Call) RunAndReturn(run func(ctx context.Context, sessionUUID uuid.UUID) (model.Session, error)) *MockSessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}
