// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/crafty-ezhik/rocket-factory/iam/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(ctx context.Context, info model.UserRegistrationInfo, hashedPassword string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, info, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserRegistrationInfo, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, info, hashedPassword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.UserRegistrationInfo, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, info, hashedPassword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.UserRegistrationInfo, string) error); ok {
		r1 = returnFunc(ctx, info, hashedPassword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - info model.UserRegistrationInfo
//   - hashedPassword string
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, info interface{}, hashedPassword interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, info, hashedPassword)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, info model.UserRegistrationInfo, hashedPassword string)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.UserRegistrationInfo
		if args[1] != nil {
			arg1 = args[1].(model.UserRegistrationInfo)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(uUID uuid.UUID, err error) *MockUserRepository_Create_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, info model.UserRegistrationInfo, hashedPassword string) (uuid.UUID, error)) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exist provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Exist(ctx context.Context, login string) (model.User, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for Exist")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Exist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exist'
type MockUserRepository_Exist_Call struct {
	*mock.Call
}

// Exist is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockUserRepository_Expecter) Exist(ctx interface{}, login interface{}) *MockUserRepository_Exist_Call {
	return &MockUserRepository_Exist_Call{Call: _e.mock.On("Exist", ctx, login)}
}

func (_c *MockUserRepository_Exist_Call) Run(run func(ctx context.Context, login string)) *MockUserRepository_Exist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Exist_Call) Return(user model.User, err error) *MockUserRepository_Exist_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_Exist_Call) RunAndReturn(run func(ctx context.Context, login string) (model.User, error)) *MockUserRepository_Exist_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Get(ctx context.Context, userUUID uuid.UUID) (model.User, error) {
	ret := _mock.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.User, error)); ok {
		return returnFunc(ctx, userUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.User); ok {
		r0 = returnFunc(ctx, userUUID)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
func (_e *MockUserRepository_Expecter) Get(ctx interface{}, userUUID interface{}) *MockUserRepository_Get_Call {
	return &MockUserRepository_Get_Call{Call: _e.mock.On("Get", ctx, userUUID)}
}

func (_c *MockUserRepository_Get_Call) Run(run func(ctx context.Context, userUUID uuid.UUID)) *MockUserRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Get_Call) Return(user model.User, err error) *MockUserRepository_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_Get_Call) RunAndReturn(run func(ctx context.Context, userUUID uuid.UUID) (model.User, error)) *MockUserRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}
