// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderAssembledConsumerConfig creates a new instance of MockOrderAssembledConsumerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderAssembledConsumerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderAssembledConsumerConfig {
	mock := &MockOrderAssembledConsumerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderAssembledConsumerConfig is an autogenerated mock type for the OrderAssembledConsumerConfig type
type MockOrderAssembledConsumerConfig struct {
	mock.Mock
}

type MockOrderAssembledConsumerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderAssembledConsumerConfig) EXPECT() *MockOrderAssembledConsumerConfig_Expecter {
	return &MockOrderAssembledConsumerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockOrderAssembledConsumerConfig
func (_mock *MockOrderAssembledConsumerConfig) Config() *sarama.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if returnFunc, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}
	return r0
}

// MockOrderAssembledConsumerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockOrderAssembledConsumerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockOrderAssembledConsumerConfig_Expecter) Config() *MockOrderAssembledConsumerConfig_Config_Call {
	return &MockOrderAssembledConsumerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockOrderAssembledConsumerConfig_Config_Call) Run(run func()) *MockOrderAssembledConsumerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderAssembledConsumerConfig_Config_Call) Return(config *sarama.Config) *MockOrderAssembledConsumerConfig_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockOrderAssembledConsumerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *MockOrderAssembledConsumerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GroupID provides a mock function for the type MockOrderAssembledConsumerConfig
func (_mock *MockOrderAssembledConsumerConfig) GroupID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOrderAssembledConsumerConfig_GroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupID'
type MockOrderAssembledConsumerConfig_GroupID_Call struct {
	*mock.Call
}

// GroupID is a helper method to define mock.On call
func (_e *MockOrderAssembledConsumerConfig_Expecter) GroupID() *MockOrderAssembledConsumerConfig_GroupID_Call {
	return &MockOrderAssembledConsumerConfig_GroupID_Call{Call: _e.mock.On("GroupID")}
}

func (_c *MockOrderAssembledConsumerConfig_GroupID_Call) Run(run func()) *MockOrderAssembledConsumerConfig_GroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderAssembledConsumerConfig_GroupID_Call) Return(s string) *MockOrderAssembledConsumerConfig_GroupID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOrderAssembledConsumerConfig_GroupID_Call) RunAndReturn(run func() string) *MockOrderAssembledConsumerConfig_GroupID_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function for the type MockOrderAssembledConsumerConfig
func (_mock *MockOrderAssembledConsumerConfig) Topic() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOrderAssembledConsumerConfig_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type MockOrderAssembledConsumerConfig_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *MockOrderAssembledConsumerConfig_Expecter) Topic() *MockOrderAssembledConsumerConfig_Topic_Call {
	return &MockOrderAssembledConsumerConfig_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *MockOrderAssembledConsumerConfig_Topic_Call) Run(run func()) *MockOrderAssembledConsumerConfig_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderAssembledConsumerConfig_Topic_Call) Return(s string) *MockOrderAssembledConsumerConfig_Topic_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOrderAssembledConsumerConfig_Topic_Call) RunAndReturn(run func() string) *MockOrderAssembledConsumerConfig_Topic_Call {
	_c.Call.Return(run)
	return _c
}
