// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderPaidProducerConfig creates a new instance of MockOrderPaidProducerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderPaidProducerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderPaidProducerConfig {
	mock := &MockOrderPaidProducerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderPaidProducerConfig is an autogenerated mock type for the OrderPaidProducerConfig type
type MockOrderPaidProducerConfig struct {
	mock.Mock
}

type MockOrderPaidProducerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderPaidProducerConfig) EXPECT() *MockOrderPaidProducerConfig_Expecter {
	return &MockOrderPaidProducerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockOrderPaidProducerConfig
func (_mock *MockOrderPaidProducerConfig) Config() *sarama.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if returnFunc, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}
	return r0
}

// MockOrderPaidProducerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockOrderPaidProducerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockOrderPaidProducerConfig_Expecter) Config() *MockOrderPaidProducerConfig_Config_Call {
	return &MockOrderPaidProducerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockOrderPaidProducerConfig_Config_Call) Run(run func()) *MockOrderPaidProducerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderPaidProducerConfig_Config_Call) Return(config *sarama.Config) *MockOrderPaidProducerConfig_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockOrderPaidProducerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *MockOrderPaidProducerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function for the type MockOrderPaidProducerConfig
func (_mock *MockOrderPaidProducerConfig) Topic() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOrderPaidProducerConfig_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type MockOrderPaidProducerConfig_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *MockOrderPaidProducerConfig_Expecter) Topic() *MockOrderPaidProducerConfig_Topic_Call {
	return &MockOrderPaidProducerConfig_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *MockOrderPaidProducerConfig_Topic_Call) Run(run func()) *MockOrderPaidProducerConfig_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderPaidProducerConfig_Topic_Call) Return(s string) *MockOrderPaidProducerConfig_Topic_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOrderPaidProducerConfig_Topic_Call) RunAndReturn(run func() string) *MockOrderPaidProducerConfig_Topic_Call {
	_c.Call.Return(run)
	return _c
}
