// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderAssembledConfig creates a new instance of MockOrderAssembledConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderAssembledConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderAssembledConfig {
	mock := &MockOrderAssembledConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderAssembledConfig is an autogenerated mock type for the OrderAssembledConfig type
type MockOrderAssembledConfig struct {
	mock.Mock
}

type MockOrderAssembledConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderAssembledConfig) EXPECT() *MockOrderAssembledConfig_Expecter {
	return &MockOrderAssembledConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockOrderAssembledConfig
func (_mock *MockOrderAssembledConfig) Config() *sarama.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if returnFunc, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}
	return r0
}

// MockOrderAssembledConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockOrderAssembledConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockOrderAssembledConfig_Expecter) Config() *MockOrderAssembledConfig_Config_Call {
	return &MockOrderAssembledConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockOrderAssembledConfig_Config_Call) Run(run func()) *MockOrderAssembledConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderAssembledConfig_Config_Call) Return(config *sarama.Config) *MockOrderAssembledConfig_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockOrderAssembledConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *MockOrderAssembledConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function for the type MockOrderAssembledConfig
func (_mock *MockOrderAssembledConfig) Topic() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOrderAssembledConfig_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type MockOrderAssembledConfig_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *MockOrderAssembledConfig_Expecter) Topic() *MockOrderAssembledConfig_Topic_Call {
	return &MockOrderAssembledConfig_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *MockOrderAssembledConfig_Topic_Call) Run(run func()) *MockOrderAssembledConfig_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderAssembledConfig_Topic_Call) Return(s string) *MockOrderAssembledConfig_Topic_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOrderAssembledConfig_Topic_Call) RunAndReturn(run func() string) *MockOrderAssembledConfig_Topic_Call {
	_c.Call.Return(run)
	return _c
}
