// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderPaidConsumerConfig creates a new instance of MockOrderPaidConsumerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderPaidConsumerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderPaidConsumerConfig {
	mock := &MockOrderPaidConsumerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderPaidConsumerConfig is an autogenerated mock type for the OrderPaidConsumerConfig type
type MockOrderPaidConsumerConfig struct {
	mock.Mock
}

type MockOrderPaidConsumerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderPaidConsumerConfig) EXPECT() *MockOrderPaidConsumerConfig_Expecter {
	return &MockOrderPaidConsumerConfig_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockOrderPaidConsumerConfig
func (_mock *MockOrderPaidConsumerConfig) Config() *sarama.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *sarama.Config
	if returnFunc, ok := ret.Get(0).(func() *sarama.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sarama.Config)
		}
	}
	return r0
}

// MockOrderPaidConsumerConfig_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockOrderPaidConsumerConfig_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockOrderPaidConsumerConfig_Expecter) Config() *MockOrderPaidConsumerConfig_Config_Call {
	return &MockOrderPaidConsumerConfig_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockOrderPaidConsumerConfig_Config_Call) Run(run func()) *MockOrderPaidConsumerConfig_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderPaidConsumerConfig_Config_Call) Return(config *sarama.Config) *MockOrderPaidConsumerConfig_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockOrderPaidConsumerConfig_Config_Call) RunAndReturn(run func() *sarama.Config) *MockOrderPaidConsumerConfig_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GroupID provides a mock function for the type MockOrderPaidConsumerConfig
func (_mock *MockOrderPaidConsumerConfig) GroupID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GroupID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOrderPaidConsumerConfig_GroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupID'
type MockOrderPaidConsumerConfig_GroupID_Call struct {
	*mock.Call
}

// GroupID is a helper method to define mock.On call
func (_e *MockOrderPaidConsumerConfig_Expecter) GroupID() *MockOrderPaidConsumerConfig_GroupID_Call {
	return &MockOrderPaidConsumerConfig_GroupID_Call{Call: _e.mock.On("GroupID")}
}

func (_c *MockOrderPaidConsumerConfig_GroupID_Call) Run(run func()) *MockOrderPaidConsumerConfig_GroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderPaidConsumerConfig_GroupID_Call) Return(s string) *MockOrderPaidConsumerConfig_GroupID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOrderPaidConsumerConfig_GroupID_Call) RunAndReturn(run func() string) *MockOrderPaidConsumerConfig_GroupID_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function for the type MockOrderPaidConsumerConfig
func (_mock *MockOrderPaidConsumerConfig) Topic() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOrderPaidConsumerConfig_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type MockOrderPaidConsumerConfig_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *MockOrderPaidConsumerConfig_Expecter) Topic() *MockOrderPaidConsumerConfig_Topic_Call {
	return &MockOrderPaidConsumerConfig_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *MockOrderPaidConsumerConfig_Topic_Call) Run(run func()) *MockOrderPaidConsumerConfig_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderPaidConsumerConfig_Topic_Call) Return(s string) *MockOrderPaidConsumerConfig_Topic_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOrderPaidConsumerConfig_Topic_Call) RunAndReturn(run func() string) *MockOrderPaidConsumerConfig_Topic_Call {
	_c.Call.Return(run)
	return _c
}
