// Code generated for crafty-ezhik service
// © Crafty-ezhik 2025.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentHTTPConfig creates a new instance of MockPaymentHTTPConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentHTTPConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentHTTPConfig {
	mock := &MockPaymentHTTPConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentHTTPConfig is an autogenerated mock type for the PaymentHTTPConfig type
type MockPaymentHTTPConfig struct {
	mock.Mock
}

type MockPaymentHTTPConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentHTTPConfig) EXPECT() *MockPaymentHTTPConfig_Expecter {
	return &MockPaymentHTTPConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockPaymentHTTPConfig
func (_mock *MockPaymentHTTPConfig) Address() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPaymentHTTPConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockPaymentHTTPConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockPaymentHTTPConfig_Expecter) Address() *MockPaymentHTTPConfig_Address_Call {
	return &MockPaymentHTTPConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockPaymentHTTPConfig_Address_Call) Run(run func()) *MockPaymentHTTPConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPaymentHTTPConfig_Address_Call) Return(s string) *MockPaymentHTTPConfig_Address_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPaymentHTTPConfig_Address_Call) RunAndReturn(run func() string) *MockPaymentHTTPConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}
