// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	OrderCancelOperation OperationName = "OrderCancel"
	OrderCreateOperation OperationName = "OrderCreate"
	OrderGetOperation    OperationName = "OrderGet"
	OrderPayOperation    OperationName = "OrderPay"
)
