// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// OrderCancelParams is parameters of OrderCancel operation.
type OrderCancelParams struct {
	// UUID сессии пользователя для аутентификации.
	XSessionUUID uuid.UUID
	// Уникальный идентификатор заказа.
	OrderUUID string
}

func unpackOrderCancelParams(packed middleware.Parameters) (params OrderCancelParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(string)
	}
	return params
}

func decodeOrderCancelParams(args [1]string, argsEscaped bool, r *http.Request) (params OrderCancelParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// OrderCreateParams is parameters of OrderCreate operation.
type OrderCreateParams struct {
	// UUID сессии пользователя для аутентификации.
	XSessionUUID uuid.UUID
}

func unpackOrderCreateParams(packed middleware.Parameters) (params OrderCreateParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeOrderCreateParams(args [0]string, argsEscaped bool, r *http.Request) (params OrderCreateParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// OrderGetParams is parameters of OrderGet operation.
type OrderGetParams struct {
	// UUID сессии пользователя для аутентификации.
	XSessionUUID uuid.UUID
	// Уникальный идентификатор заказа.
	OrderUUID string
}

func unpackOrderGetParams(packed middleware.Parameters) (params OrderGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(string)
	}
	return params
}

func decodeOrderGetParams(args [1]string, argsEscaped bool, r *http.Request) (params OrderGetParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// OrderPayParams is parameters of OrderPay operation.
type OrderPayParams struct {
	// UUID сессии пользователя для аутентификации.
	XSessionUUID uuid.UUID
	// Уникальный идентификатор заказа.
	OrderUUID string
}

func unpackOrderPayParams(packed middleware.Parameters) (params OrderPayParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Session-Uuid",
			In:   "header",
		}
		params.XSessionUUID = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(string)
	}
	return params
}

func decodeOrderPayParams(args [1]string, argsEscaped bool, r *http.Request) (params OrderPayParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Session-Uuid.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Session-Uuid",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.XSessionUUID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Session-Uuid",
			In:   "header",
			Err:  err,
		}
	}
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
