// Code generated by ogen, DO NOT EDIT.
package order_v1

type OrderCancelRes interface {
	orderCancelRes()
}

type OrderCreateRes interface {
	orderCreateRes()
}

type OrderGetRes interface {
	orderGetRes()
}

type OrderPayRes interface {
	orderPayRes()
}
