// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// OrderCancel implements OrderCancel operation.
//
// Отмена заказа.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) OrderCancel(ctx context.Context, params OrderCancelParams) (r OrderCancelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderCreate implements OrderCreate operation.
//
// Создание нового заказа.
//
// POST /api/v1/orders
func (UnimplementedHandler) OrderCreate(ctx context.Context, req *CreateOrderRequest) (r OrderCreateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderGet implements OrderGet operation.
//
// Возвращает информацию о заказе.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) OrderGet(ctx context.Context, params OrderGetParams) (r OrderGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderPay implements OrderPay operation.
//
// Оплата заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) OrderPay(ctx context.Context, req *PayOrderRequest, params OrderPayParams) (r OrderPayRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
