// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// OrderCancel implements OrderCancel operation.
	//
	// Отмена заказа.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	OrderCancel(ctx context.Context, params OrderCancelParams) (OrderCancelRes, error)
	// OrderCreate implements OrderCreate operation.
	//
	// Создание нового заказа.
	//
	// POST /api/v1/orders
	OrderCreate(ctx context.Context, req *CreateOrderRequest) (OrderCreateRes, error)
	// OrderGet implements OrderGet operation.
	//
	// Возвращает информацию о заказе.
	//
	// GET /api/v1/orders/{order_uuid}
	OrderGet(ctx context.Context, params OrderGetParams) (OrderGetRes, error)
	// OrderPay implements OrderPay operation.
	//
	// Оплата заказа.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	OrderPay(ctx context.Context, req *PayOrderRequest, params OrderPayParams) (OrderPayRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
